### ISSUE TITLE
Can I use 'th' instead of docker to run this code?

### ISSUE THREAD

**Issue by SilvesterHsu** [leongatys/NeuralImageSynthesis#1]
Nice job, but can I use 'th' instead of docker to run this code just like jcjohnson's work?

**Comment by leongatys** [comment]
In principle yes, but note that the input to the torch script is not images but the actual optimisation targets stored as hdf5 files.

**Comment by SilvesterHsu** [comment]
@leongatys  OK, thanks a lot.
